-- Export queries for Tableau
-- Run: psql -d readmission_risk -f sql/04_export_for_tableau.sql
-- Outputs to data/processed/

-- Export 1: Patient-level readmission cohort (main dataset)
\copy (WITH hf_patients AS (SELECT DISTINCT patient_id FROM conditions WHERE code = '88805009'), hf_admissions AS (SELECT e.id as encounter_id, e.patient_id, e.start_time as admission_date, e.stop_time as discharge_date, LEAD(e.start_time) OVER (PARTITION BY e.patient_id ORDER BY e.start_time) as next_admission_date, ROW_NUMBER() OVER (PARTITION BY e.patient_id ORDER BY e.start_time) as admission_sequence FROM encounters e INNER JOIN hf_patients hf ON e.patient_id = hf.patient_id WHERE e.encounterclass = 'inpatient' AND e.stop_time IS NOT NULL), patient_conditions AS (SELECT patient_id, COUNT(DISTINCT code) as condition_count FROM conditions GROUP BY patient_id) SELECT ha.encounter_id, ha.patient_id, ha.admission_date, ha.discharge_date, ha.next_admission_date, ha.admission_sequence, EXTRACT(DAY FROM (ha.next_admission_date - ha.discharge_date)) as days_to_readmission, CASE WHEN ha.next_admission_date IS NOT NULL AND EXTRACT(DAY FROM (ha.next_admission_date - ha.discharge_date)) BETWEEN 0 AND 30 THEN 1 ELSE 0 END as readmit_30_day_flag, EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) as age_at_admission, CASE WHEN EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) < 50 THEN '18-49' WHEN EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) < 65 THEN '50-64' WHEN EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) < 75 THEN '65-74' WHEN EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) < 85 THEN '75-84' ELSE '85+' END as age_group, p.gender, p.race, p.ethnicity, COALESCE(pc.condition_count, 0) as condition_count, CASE WHEN COALESCE(pc.condition_count, 0) <= 5 THEN '1-5' WHEN COALESCE(pc.condition_count, 0) <= 10 THEN '6-10' WHEN COALESCE(pc.condition_count, 0) <= 15 THEN '11-15' ELSE '16+' END as condition_group FROM hf_admissions ha INNER JOIN patients p ON ha.patient_id = p.id LEFT JOIN patient_conditions pc ON ha.patient_id = pc.patient_id) TO 'data/processed/readmission_cohort.csv' WITH (FORMAT csv, HEADER true);

-- Export 2: Rates by demographic group
\copy (WITH hf_patients AS (SELECT DISTINCT patient_id FROM conditions WHERE code = '88805009'), hf_admissions AS (SELECT e.patient_id, e.start_time as admission_date, e.stop_time as discharge_date, LEAD(e.start_time) OVER (PARTITION BY e.patient_id ORDER BY e.start_time) as next_admission_date FROM encounters e INNER JOIN hf_patients hf ON e.patient_id = hf.patient_id WHERE e.encounterclass = 'inpatient' AND e.stop_time IS NOT NULL), readmission_cohort AS (SELECT ha.*, CASE WHEN ha.next_admission_date IS NOT NULL AND EXTRACT(DAY FROM (ha.next_admission_date - ha.discharge_date)) BETWEEN 0 AND 30 THEN 1 ELSE 0 END as readmit_30_day_flag, CASE WHEN EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) < 50 THEN '18-49' WHEN EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) < 65 THEN '50-64' WHEN EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) < 75 THEN '65-74' WHEN EXTRACT(YEAR FROM AGE(ha.admission_date, p.birthdate)) < 85 THEN '75-84' ELSE '85+' END as age_group, p.gender, p.race FROM hf_admissions ha INNER JOIN patients p ON ha.patient_id = p.id) SELECT 'Age Group' as group_type, age_group as group_value, COUNT(*) as admissions, SUM(readmit_30_day_flag) as readmissions, ROUND(100.0 * SUM(readmit_30_day_flag) / COUNT(*), 2) as readmission_rate FROM readmission_cohort GROUP BY age_group UNION ALL SELECT 'Gender', gender, COUNT(*), SUM(readmit_30_day_flag), ROUND(100.0 * SUM(readmit_30_day_flag) / COUNT(*), 2) FROM readmission_cohort GROUP BY gender UNION ALL SELECT 'Race', race, COUNT(*), SUM(readmit_30_day_flag), ROUND(100.0 * SUM(readmit_30_day_flag) / COUNT(*), 2) FROM readmission_cohort GROUP BY race UNION ALL SELECT 'Overall', 'All Patients', COUNT(*), SUM(readmit_30_day_flag), ROUND(100.0 * SUM(readmit_30_day_flag) / COUNT(*), 2) FROM readmission_cohort) TO 'data/processed/rates_by_group.csv' WITH (FORMAT csv, HEADER true);

-- Export 3: Days to readmission distribution
\copy (WITH hf_patients AS (SELECT DISTINCT patient_id FROM conditions WHERE code = '88805009'), hf_admissions AS (SELECT e.patient_id, e.stop_time as discharge_date, LEAD(e.start_time) OVER (PARTITION BY e.patient_id ORDER BY e.start_time) as next_admission_date FROM encounters e INNER JOIN hf_patients hf ON e.patient_id = hf.patient_id WHERE e.encounterclass = 'inpatient' AND e.stop_time IS NOT NULL) SELECT EXTRACT(DAY FROM (next_admission_date - discharge_date))::INT as days_to_readmission, COUNT(*) as count FROM hf_admissions WHERE next_admission_date IS NOT NULL AND EXTRACT(DAY FROM (next_admission_date - discharge_date)) BETWEEN 0 AND 30 GROUP BY 1 ORDER BY 1) TO 'data/processed/days_to_readmission.csv' WITH (FORMAT csv, HEADER true);

-- Export 4: Encounter timeline for sample patients (visualization)
\copy (WITH hf_patients AS (SELECT DISTINCT patient_id FROM conditions WHERE code = '88805009'), hf_with_multiple_admissions AS (SELECT patient_id FROM encounters e INNER JOIN hf_patients hf USING (patient_id) WHERE encounterclass = 'inpatient' GROUP BY patient_id HAVING COUNT(*) >= 3 LIMIT 20) SELECT e.patient_id, e.id as encounter_id, e.start_time as admission_date, e.stop_time as discharge_date, e.encounterclass, e.description, ROW_NUMBER() OVER (PARTITION BY e.patient_id ORDER BY e.start_time) as encounter_sequence FROM encounters e INNER JOIN hf_with_multiple_admissions hfm ON e.patient_id = hfm.patient_id WHERE e.encounterclass IN ('inpatient', 'emergency') ORDER BY e.patient_id, e.start_time) TO 'data/processed/encounter_timeline.csv' WITH (FORMAT csv, HEADER true);

-- Export 5: Summary metrics for KPI cards
\copy (WITH hf_patients AS (SELECT DISTINCT patient_id FROM conditions WHERE code = '88805009'), hf_admissions AS (SELECT e.patient_id, e.stop_time as discharge_date, LEAD(e.start_time) OVER (PARTITION BY e.patient_id ORDER BY e.start_time) as next_admission_date FROM encounters e INNER JOIN hf_patients hf ON e.patient_id = hf.patient_id WHERE e.encounterclass = 'inpatient' AND e.stop_time IS NOT NULL), readmission_flags AS (SELECT patient_id, CASE WHEN next_admission_date IS NOT NULL AND EXTRACT(DAY FROM (next_admission_date - discharge_date)) BETWEEN 0 AND 30 THEN 1 ELSE 0 END as readmit_30_day_flag FROM hf_admissions) SELECT 'Total HF Patients' as metric, COUNT(DISTINCT patient_id)::TEXT as value FROM hf_patients UNION ALL SELECT 'Index Admissions', COUNT(*)::TEXT FROM readmission_flags UNION ALL SELECT '30-Day Readmissions', SUM(readmit_30_day_flag)::TEXT FROM readmission_flags UNION ALL SELECT 'Readmission Rate (%)', ROUND(100.0 * SUM(readmit_30_day_flag) / COUNT(*), 1)::TEXT FROM readmission_flags) TO 'data/processed/summary_metrics.csv' WITH (FORMAT csv, HEADER true);

-- Export 6: Admission frequency distribution (patients by total admissions)
\copy (WITH hf_patients AS (SELECT DISTINCT patient_id FROM conditions WHERE code = '88805009'), patient_admissions AS (SELECT e.patient_id, COUNT(*) as total_admissions FROM encounters e INNER JOIN hf_patients hf ON e.patient_id = hf.patient_id WHERE e.encounterclass = 'inpatient' AND e.stop_time IS NOT NULL GROUP BY e.patient_id), grouped AS (SELECT CASE WHEN total_admissions >= 10 THEN '10+' ELSE total_admissions::TEXT END as admission_count, CASE WHEN total_admissions >= 10 THEN 10 ELSE total_admissions END as sort_order, COUNT(*) as patient_count FROM patient_admissions GROUP BY 1, 2) SELECT admission_count, patient_count FROM grouped ORDER BY sort_order) TO 'data/processed/admission_frequency.csv' WITH (FORMAT csv, HEADER true);

-- Export 7: Readmission rate by admission number (1st, 2nd, 3rd visit, etc.)
\copy (WITH hf_patients AS (SELECT DISTINCT patient_id FROM conditions WHERE code = '88805009'), hf_admissions AS (SELECT e.patient_id, e.stop_time as discharge_date, LEAD(e.start_time) OVER (PARTITION BY e.patient_id ORDER BY e.start_time) as next_admission_date, ROW_NUMBER() OVER (PARTITION BY e.patient_id ORDER BY e.start_time) as admission_number FROM encounters e INNER JOIN hf_patients hf ON e.patient_id = hf.patient_id WHERE e.encounterclass = 'inpatient' AND e.stop_time IS NOT NULL), readmission_calc AS (SELECT admission_number, CASE WHEN next_admission_date IS NOT NULL AND EXTRACT(DAY FROM (next_admission_date - discharge_date)) BETWEEN 0 AND 30 THEN 1 ELSE 0 END as readmit_30_day_flag FROM hf_admissions WHERE admission_number <= 5) SELECT admission_number, COUNT(*) as admissions, SUM(readmit_30_day_flag) as readmissions, ROUND(100.0 * SUM(readmit_30_day_flag) / COUNT(*), 2) as readmission_rate FROM readmission_calc GROUP BY admission_number ORDER BY admission_number) TO 'data/processed/rate_by_admission.csv' WITH (FORMAT csv, HEADER true);
